name: Deploy to neocities

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *' # update every 15 minutes
  workflow_dispatch: # adds the button to github to run manually 

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # install node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # generate the music-data.json file
      - name: Fetch Last.fm Now Playing
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_USER: 'buggbuggbugg' 
        run: |
          npm init -y
          npm install node-fetch
          node update-widget.js

      # neocities stuff. future bugg do not change. do not touch. do not do not do not. 
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          neocities_supporter: false
          preview_before_deploy: true
          dist_dir: .
